### ISSUE TITLE
Unable to merge dictionaries from different files

### ISSUE THREAD

**Issue by littlebigfab** [totango/helm-ssm#8]
Hello,

When loading multiple values files containing the same key name but different contents, running `helm install` merges the dictionaries, but the `helm-ssm` plugin does not.

**How to reproduce:**

* `file1.yml`
```yaml
key1:
  value1: foo
  value2: bar
 ```

* `file2.yml`
```yaml
key1:
  value3: biz
 ```

* Install a helm chart with the ssm plugin on, loading the two values files:
```bash
helm ssm install -f file1.yml -f file2.yml [NAME] [CHART]
```

**Expected:**

The following dictionary is loaded into the helm chart:

```yaml
key1:
  value1: foo
  value2: bar
  value3: biz
 ```

**Actual result:**

Only the dictionary contained in `file2.yaml` is actually loaded into the helm chart:
```yaml
key1:
  value3: biz
 ```
